# -*- coding: utf-8 -*-
# Vietnamese script. Keys = original bank-3 string addresses.
NAMES = ["SHIN:","SHIRO:","MISAE:","BỐ:","RIE:","MASAO:","NENE:","KAZAMA:","CÔ YOSHINAGA:","CÔ MATSUZAKA:",
 "HIỆU TRƯỞNG:","TAWASHI:","MẸ NENE:","CÔ NAKAMURA:","ACTION KAMEN:","CÁC BÉ:","CẢ LỚP:","CHEETAH:","CHỦ TIỆM:","MIMIKO:","TAY SAI:"]
D = {
0x8C92:"CHÀO MỪNG VỀ NHÀ~",0x8C9A:"NÀY! SHINNOSUKE! VỀ NHÀ THÌ PHẢI NÓI \"CON ĐÃ VỀ\" CHỨ!!",
0x8CB9:"CON QUA NHÀ MASAO CHƠI ĐÂY. BÁI BAI!",0x8CCF:"ƯM~ SAO MÀ ỒN THẾ NHỈ~",0x8CE2:"Ồ! SHIRO!",
0x8CEC:"HỘC HỘC HỘC",0x8CF7:"ẲNG, ẲNG ẲNG!",0x8D05:"Ồ Ồ",0x8D0A:"Ồ, Ồ. KHÔNG SAO ĐÂU SHIRO. PHẢI CẨN THẬN XE CỘ ĐÓ!",
0x8D30:"ẲNG!!",0x8D38:"ỪM, ỪM.",0x8D40:"ẲNG ẲNG!!",0x8D4C:"HẢ? …GÌ VẬY SHIRO, MUỐN ĐI DẠO HẢ? CHÀ, ĐÚNG LÀ ĐỒ NHÕNG NHẼO!",
0x8D77:"NHƯNG MÀ TỚ CÒN BAO NHIÊU CHUYỆN XÃ GIAO, BẬN LẮM ĐÓ!",0x8D9B:"………",
0x8DA5:"ĐƯỢC! THI ĐẤU VỚI TỚ ĐI. NẾU SHIRO THẮNG, TỚ SẼ DẮT ĐI DẠO!",0x8DD3:"ẲNG!!",
0x8DDB:"A HA! A HA! THẮNG RỒI! THẮNG RỒI~!!",0x8DF4:"………",0x8DFE:"SHIN À……",0x8E09:"Ư……",
0x8E11:"ĐỪNG CÓ BẮT NẠT NÓ, DẮT NÓ ĐI DẠO ĐI!",0x8E2E:"TRỜI ƠI!!!……",0x8E3A:"TH… THUA CẢ SHIRO……",0x8E4A:"ẲNG ẲNG ẲNG!!",
0x8FBC:"TRỜI, BẬN QUÁ! TRỜI, BẬN QUÁ ĐI!",0x8FD4:"SHIN ƠI~ LẠI ĐÂY MẸ BẢO NÀY~",0x8FEA:"GIỜ CON ĐANG BẬN, KHÔNG ĐƯỢC!!",
0x8FFC:"HỬ……? CON ĐANG LÀM GÌ ĐÓ~",0x900C:"HA HA HA HA HA! ACTION~ KAMEN~!!",0x9026:"……SHINNOSUKE?",0x9033:"GIẬT THÓT!",
0x903A:"MẸ GỌI THÌ PHẢI ĐẾN NGAY CHỨ!",0x9050:"CỐC!",0x9058:"BƯNG CHÉN BÁT GIÚP MẸ NHÉ.",0x9067:"VÂNG~……",
0x9070:"GIỎI QUÁ, SHIN!",0x907D:"XOẢNG!!",0x9086:"KHÔNG LẼ!?",0x9090:"SHINNOSUKE!!",0x9099:"Ư!",
0x909E:"PHẢI GIÚP MẸ ĐẾN CÙNG CHỨ!!",0x90BD:"ÁI!!",0x90C4:"TRỜI ƠI, LÀM VỠ CHÉN CỦA BỐ RỒI~",0x90DE:"MẸ THẬT LÀ VỤNG VỀ.",
0x90EF:"LÀ CON ĐẤY!!",0x90FA:"MẸ KHÔNG BIẾT ĐÂU NHA~",0x9104:"BỐ MÀ GIẬN THÌ CÓ KHI SẼ KHÔNG CHƠI VỚI SHIN NỮA ĐÂU……",
0x9128:"HẢ!? VẬY CÒN LỜI HỨA DẪN CON ĐI XEM ACTION KAMEN BIỂU DIỄN THÌ SAO?",0x9153:"CHẮC HỎNG RỒI~ BỐ THÍCH CÁI CHÉN NÀY LẮM MÀ~",
0x917B:"M… MẸ ƠI, MẸ ƠI!! ĐẤU VỚI CON ĐI!! NẾU CON THẮNG THÌ ĐỪNG MÁCH BỐ NHA!!",0x91B3:"HỬ…… CŨNG ĐƯỢC THÔI……?",
0x91C7:"MẸ MẠNH LẮM ĐẤY NHÉ~",0x91D5:"KHOAN, KHOAN ĐÃ SHINNOSUKE! ĐẤU LẠI LẦN NỮA! LẦN NỮA!!",0x91FE:"RẮC!",0x9205:"Ư!",0x920A:"Á!!",
0x920F:"NÀY!! SHINNOSUKE!! LÀM VỠ LUÔN CẢ CHÉN CỦA MẸ!! CON LÀM CÁI TRÒ GÌ VẬY!!",0x923C:"M… MẸ ƠI, CƠM ĐÂU Ạ?",
0x924D:"ĐỪNG CÓ LẢNG SANG CHUYỆN KHÁC!!",0x925E:"TRỜI ƠI!! THUA RỒI……",0x926D:"Ê Ê! MẸ THẮNG RỒI NHÉ~",
0x927E:"ĐẤU VỚI CON NÍT MÀ CŨNG NGHIÊM TÚC, MẸ THẬT LÀ TRẺ CON!",0x92A0:"CÁI GÌ!! NÓI CHO CÙNG THÌ CŨNG TẠI CON ĐẤY!!",
0x92C4:"OÁI!!",0x92CE:"SHIN ƠI~ SHIN ƠI~ CHƠI ĐI~ SHIN ƠI~",0x92EB:"……SHIN, CẬU ĐANG LÀM GÌ VẬY?",0x92FE:"CHƠI LÀM GẤU KOALA.",
0x9308:"Đ… ĐỪNG LÀM THẾ, NGUY HIỂM LẮM!",0x931E:"ĐƯỢC! CHƠI GÌ ĐÂY?",0x932F:"ƯM~ ƯM~ CHƠI ĐÓNG VAI ACTION KAMEN ĐI!",
0x935D:"SH… SHIN, SHIN ƠI~ TỚ CŨNG MUỐN LÀM ACTION KAMEN CƠ~",0x9385:"THÌ CỨ LÀM ĐI?",0x938D:"HẢ!? ĐƯỢC HẢ?",
0x9398:"LẠI ĐÂY! ACTION KAMEN DỎM!!",0x93AB:"SHIN ƠI~",0x93B4:"VẬY ĐẤU VỚI TỚ ĐI. THẮNG THÌ TỚ NHƯỜNG CHO!",
0x93D5:"HẢ, THẬT KHÔNG?",0x93DF:"T… TỚ KHÔNG THUA ĐÂU!",0x93EE:"THUA MẤT RỒI……",0x93FB:"CHÀO SHINNOSUKE! CHƠI CẦU TRƯỢT KHÔNG?",
0x9419:"Ồ! CẦU TRƯỢT, CẦU TRƯỢT!",0x942E:"SH… SHIN ƠI~ ÁC QUÁ À~",0x9440:"Ồ… TH… THUA RỒI.",0x944B:"A HA! TỚ LÀ ACTION KAMEN NHÉ, SHIN!",
0x946A:"MASAO GIAN QUÁ! ĂN GIAN ĐỂ ĐƯỢC LÀM ACTION KAMEN À!",0x9494:"QU… QUÁ ĐÁNG, SHIN! TỚ ĐÂU CÓ LÀM VẬY~",
0x96B7:"GÌ THẾ~?",0x96BF:"CHƠI ĐỒ HÀNG VỚI NENE KHÔNG?",0x96D1:"ĐƯỢC THÔI~",0x96D8:"CÓ CẢ KAZAMA NỮA ĐẤY.",
0x96E7:"Ồ! VẬY TỚ ĐÓNG VAI BỐ NHÉ!",0x9703:"NÀY SHINNOSUKE! SAO LẠI THẾ ĐƯỢC!!",0x971F:"Ồ, KAZAMA ĐẤY À.",
0x972B:"LẦN NÀY ĐÃ QUYẾT LÀ TỚ LÀM BỐ RỒI.",0x9749:"XIN LỖI NHÉ SHIN. KAZAMA BẢO KHÔNG ĐƯỢC LÀM BỐ THÌ KHÔNG CHỊU.",
0x9774:"HỪM~",0x977A:"KAZAMA ĐÚNG LÀ ĐỒ ÍCH KỶ.",0x978E:"C… CÁI GÌ HẢ?",0x9798:"CHẬC~ CÓ ĐỨA ÍCH KỶ THẾ NÀY, NENE CŨNG KHỔ GHÊ ĐÓ.",
0x97BC:"SHIN À……",0x97C6:"ƯƯ……",0x97CD:"ÔI~ CHÁN QUÁ, CHÁN QUÁ.",0x97DA:"THÔI ĐỦ RỒI!!",0x97E4:"Á, KAZAMA!",
0x97EF:"SHIN!! ĐI GỌI KAZAMA VỀ ĐÂY! CẬU ẤY ĐÃ HỨA VỚI NENE RỒI MÀ!!",0x9818:"VẬY THÌ ĐẤU ĐI. NẾU NENE THẮNG, TỚ SẼ ĐI GỌI CHO!",
0x9843:"THUA MẤT RỒI…… VẬY SHIN LÀM BỐ NHÉ.",0x9860:"CHÀO MỪNG VỀ NHÀ~",0x9868:"PHẢI NÓI \"ANH VỀ RỒI ĐÂY\" CHỨ, BỐ NÓ!",
0x9877:"",0x9878:"LENG KENG",0x9882:"CHỊ ƠI, CHỊ ĂN ĐƯỢC ỚT XANH KHÔNG?",0x9898:"……SHIN À.",
0x98A2:"A HA, A HA! THẮNG RỒI! THẮNG ĐƯỢC SHIN RỒI!",0x98BD:"SHINNOSUKE ĐỒ GÀ MỜ~",0x98CE:"ACTION~ KAMEN~ NGƯỜI HÙNG~ CHÍNH NGHĨA~",
0x98EC:"Ồ, KAZAMA.",0x98F7:"CH… CHÀO…… SHINNOSUKE……",0x9907:"KAZAMA…… CẬU CẦM CÁI GÌ VẬY?",
0x991D:"Ư…… C… CÁI NÀY HẢ? ĐÂY LÀ ĐỒ QUAN TRỌNG ĐÓ.",0x993A:"CHO XEM VỚI.",0x9940:"KHÔNG ĐƯỢC!!",0x9946:"",
0x9949:"KAZAMA…… KHÔNG CHO XEM LÀ TỚ MÁCH CÔ YOSHINAGA BÍ MẬT CỦA CẬU ĐÓ!",0x997C:"B… BÍ MẬT GÌ CHỨ, SHINNOSUKE!? TỚ LÀM GÌ CÓ BÍ MẬT NÀO!",
0x99A5:"SAO CẬU CUỐNG LÊN THẾ? TỚ CÓ BIẾT GÌ ĐÂU MÀ.",0x99C6:"……CHO CẬU XEM ĐẤY.",0x99D2:"ĐÂY NÀY.",0x99D7:"Ồ! BUM-AN!",
0x99E2:"AN - BUM !!",0x99EF:"SAO TRÔNG GIỐNG KAZAMA THẾ NHỈ~",0x9A05:"LÀ TỚ ĐÓ!!",0x9A0F:"LÀ ẢNH CỦA TỚ TỪ LÚC MỚI SINH ĐÓ.",
0x9A27:"Ồ~~~~",0x9A30:"THẤY CHƯA! TỪ HỒI XƯA ĐÃ ĐẸP TRAI RỒI NHỈ?",0x9A49:"CÓ CẢ ẢNH TÈ DẦM NÀY.",
0x9A5B:"H… HỒI CÒN BÉ THÌ AI CHẲNG THẾ!!",0x9A75:"THẾ BÂY GIỜ KHÔNG PHẢI CON NÍT À?",0x9A89:"TH… THÌ VẪN LÀ CON NÍT, NHƯNG MÀ……",
0x9A9E:"ĐỒ NÓI DỐI.",0x9AA5:"HỰ!",0x9AAB:"A HA, A HA! KAZAMA TÈ DẦM~",0x9AC2:"GRỪ……",
0x9ACC:"SHINNOSUKE!! ĐẤU ĐI!! NẾU TỚ THẮNG THÌ ĐỪNG BAO GIỜ NÓI XẤU TỚ NỮA!!",0x9B04:"ƯƯ…… THUA RỒI……",
0x9B10:"Á, BO ƠI! MUỐN BIẾT BÍ MẬT CỦA KAZAMA KHÔNG?",0x9B2D:"SHINNOSUKE!!",0x9B37:"A HA, A HA!",
0x9B41:"NÀY! SHINNOSUKE! TỚ THẮNG RỒI MÀ!",0x9B5D:"Đ… ĐỪNG CÓ LỜ TỚ ĐI!!",0x9B6E:"TẠM BIỆT CÁC EM NHÉ.",
0x9B7E:"CHÀO CÔ YOSHINAGA Ạ!",0x9B93:"NÀO, PHẢI MAU CHUẨN BỊ ĐI VỀ THÔI.",0x9BAD:"CÔ YOSHINAGA ƠI~",0x9BBA:"Ơ KÌA, SHIN……",
0x9BC7:"HẢ!?",0x9BCE:"TỚ BỊ LẤM LEM BÙN ĐẤT, KHÓ CHỊU QUÁ À.",0x9BE8:"EM LÀM CÁI GÌ VẬY HẢ?",0x9BF4:"TRỜI Ạ, HÔM NAY CÔ ĐANG VỘI MÀ……",
0x9C10:"SAO CÔ VỘI THẾ?",0x9C21:"HẢ?",0x9C26:"HÔM NAY CÔ CÓ VIỆC, PHẢI ĐI RA NGOÀI.",0x9C4C:"HẢ, ĐI CHƠI À? ĐI ĐÂU VẬY?",
0x9C60:"CÔ ĐI ĂN TỐI.",0x9C6F:"HÌ HÌ~ ĂN GÌ ĐÂY TA? TỚ GỌI SUẤT CƠM TRẺ EM NHÉ~",0x9C94:"CÔ KHÔNG DẪN SHIN ĐI ĐÂU NHÉ.",
0x9CB2:"",0x9CB3:"",0x9CB4:"",0x9CB5:"",0x9CB8:"HẸN HÒ À NHA.",0x9CC2:"HỰ! SH… SHIN, PHẢI VỀ THÔI KẺO MẸ EM LO ĐẤY~",
0x9CEE:"HÔM NAY TỚ CHƠI THÊM CHÚT NỮA NHÉ~",0x9D09:"CHỈ CÒN MỖI SHIN THÔI ĐÓ~ ÁÁÁ, TRỄ GIỜ RỒI~ TRỄ GIỜ~",
0x9D31:"VẬY ĐẤU VỚI TỚ ĐI. CÔ THẮNG THÌ TỚ VỀ.",0x9D56:"ĐƯỢC RỒI. NHƯNG CHỈ MỘT LẦN THÔI ĐẤY.",0x9D6F:"ÁÁÁ, THUA MẤT RỒI.",
0x9D7C:"CÔ YOSHINAGA ƠI~",0x9D89:"GÌ NỮA?",0x9D8F:"TỚI GIỜ ĂN VẶT RỒI, TỚ VỀ ĐƯỢC CHƯA?",0x9DAB:"CÓ AI GIỮ EM LẠI ĐÂU!!",
0x9DC0:"NÀO SHIN, VỀ THÔI NHÉ.",0x9DD3:"ĐẤU THÊM MỘT LẦN NỮA THÌ TỚ VỀ.",0x9DE8:"HẦY……",
0x9FF0:"NÀO, CÁC EM!",0x9FFA:"CÁC EM ĐÃ VẼ ĐẸP TRANH VỀ THỨ MÌNH THÍCH CHƯA?",0xA012:"DẠ~!",0xA018:"VẬY MÌNH TREO LÊN TƯỜNG LỚP NHÉ.",
0xA02E:"CÔ YOSHINAGA ƠI.",0xA03A:"GÌ VẬY NENE?",0xA046:"BẠN SHIN KHÔNG CÓ Ở ĐÂY Ạ.",0xA053:"",0xA054:"XOẠCH",
0xA05B:"Ơ, CÔ MATSUZAKA.",0xA06A:"CÔ YOSHINAGA…… RA ĐÂY MỘT CHÚT.",0xA080:"GÌ CHỨ?",0xA086:"CỨ RA ĐÂY ĐÃ!",
0xA097:"NÀY, DỪNG LẠI! BÀN CỦA TAO ĐẤY!!",0xA0AF:"CỨ ĐỂ ĐÓ CHO TỚ.",0xA0BC:"ĐỂ CÁI GÌ HẢ!!",0xA0C6:"SH… SHIN, KHÔNG ĐƯỢC VẼ LÊN BÀN CHỨ!!",
0xA0E7:"HỬ?",0xA0EC:"THẬT TÌNH, LỚP HƯỚNG DƯƠNG TỆ QUÁ!",0xA102:"CÔ NÓI GÌ!!",0xA10D:"TỚ CHỈ LÀM CÁI BÀN CỦA CHEETAH NGẦU HƠN THÔI MÀ!",
0xA131:"HỪ! KAWAMURA NHỜ EM LÀM À?",0xA14C:"AI THÈM NHỜ CHỨ! ỪM~ CÔ MATSUZAKA NGỐC GHÊ. THẢO NÀO CHẲNG CÓ NGƯỜI YÊU……",
0xA188:"CÁI GÌ CƠ……",0xA195:"N… NẾU CÔ ĐẤU THẮNG TỚ THÌ TỚ XIN LỖI CŨNG ĐƯỢC.",0xA1BA:"ĐẤU THÌ ĐẤU! NHƯNG NẾU THUA, EM PHẢI LAU SẠCH CÁI BÀN ĐẤY!!",
0xA1E3:"GIỎI QUÁ, SHIN!",0xA1F2:"T… TỨC QUÁ ĐI……",0xA1FE:"CÔ ƠI, CÁI BÀN CỦA EM……",0xA213:"TỰ ĐI MÀ LAU!!",0xA224:"HẢ~!?",
0xA22E:"HÔ HÔ HÔ HÔ! THẮNG DỄ ỢT!!",0xA244:"CHỈ LÀ TRÒ CHƠI CON NÍT MÀ……",0xA257:"XIN LỖI NHÉ, VÌ CÔ TRẺ CON QUÁ……",
0xA270:"BIẾT VẬY LÀ ĐƯỢC. TỚ RỘNG LƯỢNG LẮM, THA CHO ĐÓ.",0xA296:"THÔI NÀO……",0xA29E:"",0xA29F:"CỘP CỘP CỘP",
0xA2AA:"SẮP XONG RỒI ĐÂY.",0xA2BC:"",0xA2BD:"CỘP CỘP CỘP CỘP",0xA2CB:"ÔNG TRÙM~",0xA2D3:"HẢ, CHUYỆN GÌ ĐÓ…… À KHÔNG!",
0xA2E7:"SHINNOSUKE À…… THẦY KHÔNG PHẢI ÔNG TRÙM, MÀ LÀ HIỆU TRƯỞNG.",0xA310:"THẦY ĐANG LÀM GÌ VẬY?",
0xA31A:"CÁI NÀY À? THẦY ĐANG LÀM CHUỒNG THỎ.",0xA33A:"Ồ, CHUỒNG THỎ……",0xA34A:"T… TỚ GIÚP THẦY MỘT TAY CŨNG ĐƯỢC ĐÓ.",
0xA363:"TH… THÔI, VIỆC NÀY VẤT VẢ LẮM, KHÔNG CẦN ĐÂU.",0xA37F:"KHÔNG CHỊU! TỚ LÀM, TỚ LÀM! TỚ LÀM, TỚ LÀM, TỚ LÀM!!",
0xA3A4:"ƯM…… ĐÀNH VẬY!",0xA3B7:"VẬY NẾU THẮNG ĐƯỢC THẦY THÌ THẦY CHO GIÚP.",0xA3D6:"TỚ MẠNH LẮM ĐÓ!",0xA3E3:"ĐÀNH VẬY THÔI!",
0xA3F2:"Á",0xA3F6:"ÔNG TRÙM, TỚ ĐI ĂN XẾ ĐÂY. BÁI BAI!",0xA411:"………",0xA41C:"……RÕ RÀNG THẦY THẮNG MÀ.",
0xA42F:"ỪM, LÀM KHÉO GHÊ.",0xA43E:"GIỜ CHỈ CẦN CHO VÀO LÒ VI SÓNG…… LÀ XONG.",0xA452:"NE~NE~ ƠI~",0xA45C:"Ơ KÌA…… GIỌNG NÀY LÀ SHIN……",
0xA470:"",0xA471:"HẢ!?",0xA47B:"SHIN, CHÁU ĐANG LÀM GÌ VẬY?",0xA48E:"Ồ!",0xA494:"CHÁU MANG ĐỒ NENE BỎ QUÊN ĐẾN TRẢ ĐÂY Ạ.",
0xA4B1:"Ồ, ĐÚNG LÀ KHĂN TAY CỦA NENE RỒI.",0xA4C3:"CẢM ƠN CHÁU NHÉ, SHIN.",0xA4D2:"TRỜI ƠI!! KHÁT NƯỚC QUÁ, KHÔNG ĐI NỔI NỮA~",
0xA4ED:"Đ… ĐỂ CÔ RÓT SỮA CHO NHÉ.",0xA4FF:"CHÁU MUỐN NƯỚC ÉP 100% CƠ.",0xA51A:"RỒI, RỒI.",0xA520:"",0xA521:"ỰC ỰC ỰC",
0xA52F:"NENE VỀ MUỘN GHÊ~",0xA53B:"CÔ ƠI, CHƠI VỚI CHÁU ĐI~",0xA54E:"HẢ?",0xA553:"CŨNG ĐƯỢC! NENE CÒN LÂU MỚI VỀ……",
0xA565:"MỘT CHÚT THÔI NHÉ.",0xA574:"SH… SHIN GIỎI GHÊ NHỈ.",0xA584:"NGƯỜI LỚN GÌ MÀ CHƠI DỞ ẸC.",0xA597:"MÀY NÓI GÌ~! THẰNG NHÓC NÀY!!",
0xA5A9:"M… MẸ!?",0xA5B2:"HẢ?",0xA5B7:"Đ… ĐÂY KHÔNG PHẢI MẸ MỌI KHI……",0xA5CA:"N… NENE……",0xA5D4:"TỚ VỀ ĐÂY.",
0xA5DD:"KHÔNG PHẢI MẸ MỌI KHI~",0xA5EF:"TH… THẮNG… THẮNG RỒI! HÔ HÔ HÔ HÔ HÔ!",
0xA6EC:"CỨU TÔI VỚI~!",0xA6F5:"Ồ, ĐÓ CHẲNG PHẢI CHỊ MIMIKO SAO!?",0xA70A:"Á!? EM ƠI!! NGUY HIỂM LẮM, CHẠY ĐI!!",0xA721:"",
0xA722:"XẸT XẸT XẸT",0xA731:"XẸT~~~!!",0xA73A:"Ồ~! T… TỚ BẮN ĐƯỢC ACTION BEAM RỒI!?",0xA759:"HA HA HA HA!",0xA766:"HỬ?",
0xA76B:"SHINNOSUKE!! CẢM ƠN CẬU ĐÃ CỨU MIMIKO!! TA XIN CẢM TẠ TỪ ĐÁY LÒNG!",0xA79C:"ACTION KAMEN!!",
0xA7A9:"SHINNOSUKE, CÓ LẼ CẬU SẼ TRỞ THÀNH ACTION KAMEN ĐẤY.",0xA7D4:"ĐỂ TĂNG SỨC MẠNH, CẬU ĐẤU VỚI TA MỘT TRẬN CHỨ?",
0xA7F8:"Ồ!",0xA7FE:"ACTION~ KAMEN~!!",0xA80D:"QUẢ NHIÊN TA KHÔNG NHÌN NHẦM NGƯỜI!!",0xA822:"TUYỆT QUÁ! ACTION KAMEN SỐ 2!!",
0xA839:"HA HA HA HA HA!",0xA846:"HA HA HA…… HẢ!",0xA853:"SHINNOSUKE~?",0xA85D:"DẬY ĐI~ SÁNG RỒI ĐÓ!",
0xA86E:"ƯM…… ƯM…… LẠI ĐÂY~ QUÁI NHÂN BÀ GIÀ MÔNG BỰ~",0xA88F:"CON NÓI CÁI GÌ~!!",0xA89B:"THUA RỒI……",0xA8A4:"M… MUỐN ĐẤU LẠI LẦN NỮA KHÔNG?",
0xB0DC:"Ồ",0xB0DE:"Ồ Ồ",0xB0E1:"VẬY NHÉ",
}
D1 = {
0xAA23:"VÀO TRẬN NÀO!",0xAA35:"ĐẨY KHỐI NÈ!",0xAA41:"THẤY CHƯA~",0xAA45:"DỞ QUÁ À.",0xAA4D:"ĐẨY ĐI CHỨ?",0xAA53:"Ồ! GIAN THẾ!",
0xAA5E:"KHÔNG CHỊU~!",0xAA69:"ACTION BEAM!!",0xAA74:"ĐỪNG CAY CÚ!",0xAA7D:"XÓA LIÊN HOÀN!",0xAA8F:"A HA, THẮNG!!",0xAA9E:"ÁI!! THUA RỒI",
0xAAA8:"ẲNG!",0xAAAD:"ẲNG",0xAAB1:"ẲNG ẲNG",0xAAB9:"ẲNG ẲNG ẲNG",0xAAC5:"ẲNG!?",0xAACB:"ẲNG!",0xAAD0:"ẲNG ẲNG!!",0xAAD9:"ẲNG ẲNG ẲNG!!",
0xAAE6:"ẲNG~",0xAAEB:"ẲNG ẲNG!",0xAAF4:"ẲNG ẲNG ẲNG!!",0xAB01:"………",0xAB0A:"MẸ SẼ THẮNG!",0xAB12:"ĐẨY KHỐI ĐÂY!",0xAB22:"MẸ GIỎI THẬT!",
0xAB2D:"THẤY ĐÒN CHƯA?",0xAB3D:"KHOAN ĐÃ~!",0xAB48:"Á Á Á Á Á!",0xAB4F:"MẶC KỆ MẸ!",0xAB57:"TIA CỐC ĐẦU!",0xAB62:"Á~! DÁM À~!!",
0xAB6D:"LIÊN HOÀN NÈ!",0xAB7C:"MẸ MẠNH! HÔ HÔ",0xAB8B:"ÔI, THUA RỒI…",0xAB99:"TỚ KHÔNG THUA!",0xABA2:"HÊ HÊ, ĐẨY NÈ!",0xABAD:"ĐẦY KHỐI RỒI!",
0xABB8:"SẮP XONG RỒI!",0xABC3:"ÔI CHAO~",0xABC7:"Đ-ĐỢI ĐÃ SHIN!",0xABD4:"ÁÁ, SẮP THUA~",0xABE0:"ĐẨY HẾT SỨC!!",0xABEC:"Đ-ĐỪNG MÀ~",
0xABF4:"HÊ, LIÊN HOÀN!",0xAC04:"A HA! THẮNG~",0xAC11:"ÁÁ, THUA RỒI~",0xAC1D:"NENE SẼ THẮNG!",0xAC28:"ĐẨY KHỐI ĐÓ.",0xAC33:"ĐẨY TỚI ĐÂY!",
0xAC41:"NENE THẮNG NHÉ",0xAC4D:"Á~ ĐẨY RỒI~",0xAC55:"SHIN ÁC QUÁ~",0xAC61:"SH-SHIN ĐỢI ĐÃ",0xAC6E:"TUYỆT CHIÊU~!",0xAC7C:"SHIN ÁC QUÁ~!",
0xAC89:"LIÊN HOÀN NÈ~!",0xAC96:"A HA! THẮNG~",0xACA3:"HU HU, THUA~",0xACAC:"LẠI ĐÂY, SHIN!",0xACB9:"ĐẨY KHỐI ĐÂY!",0xACC5:"THẾ NÀO, SHIN!",
0xACD3:"CHỊU THUA ĐI!!",0xACDD:"CHẬC!!",0xACE2:"C-CŨNG KHÁ ĐẤY",0xACED:"ƯƯ, SẮP THUA~",0xACF8:"ĐÒN TẤT SÁT!!",0xAD04:"Á, CHẾT TIỆT~!",
0xAD0E:"LIÊN HOÀN ĐÂY!",0xAD1C:"DỄ ỢT MÀ!!",0xAD29:"ƯƯ… THUA RỒI…",0xAD35:"ĐẤU MỘT VÁN!!",0xAD42:"ĐẨY KHỐI NHÉ.",0xAD4D:"TỚI LUÔN NÀO!",
0xAD5C:"CÔ THẮNG ĐÂY!!",0xAD68:"CHẾT CHA~",0xAD6D:"KH-KHOAN ĐÃ!",0xAD7A:"S-SAO THẾ~!?",0xAD86:"QUỶ CÚT RA~!!",0xAD90:"Á~ ÁC QUÁ!!",
0xAD9A:"LIÊN HOÀN NÈ!",0xADA8:"A HA! THẮNG!",0xADB5:"CHẾT, THUA~",0xADBF:"CHIỀU EM ĐÂY.",0xADCC:"ĐẨY KHỐI ĐÂY!",0xADDA:"HỪ HỪ, NÀY~",
0xADE3:"DỞ QUÁ ĐI!",0xADF2:"Ơ, KHÁ ĐẤY!",0xADFF:"KHOAN ĐÃ NÀO!",0xAE0C:"THÔI MÀ, NÀY~",0xAE19:"ĐÒN NÀY SAO?",0xAE28:"Á~! DÁM À!!",
0xAE34:"HÔ, LIÊN HOÀN!",0xAE43:"HÔ HÔ! THẮNG!!",0xAE50:"ƯƯ… THUA RỒI…",0xAE5C:"CỐ LÊN NÀO!",0xAE6A:"CÔ ĐẨY ĐẤY!",0xAE77:"ỪM~ ỔN CHỨ?",
0xAE85:"XIN LỖI SHIN!",0xAE93:"Á~ BỊ HẠ RỒI!",0xAE9D:"C-CÁI NÀY THÌ…",0xAEAA:"NƯƠNG TAY CHỨ!",0xAEB8:"CHIÊU YẾN HỒI!",0xAEC4:"ÁÁÁÁÁÁÁÁÁ",
0xAECE:"LIÊN HOÀN ĐÓ!",0xAEDE:"XIN LỖI SHIN!",0xAEEC:"HU HU… THUA~",0xAEFA:"ĐÀNH CHỊU VẬY~",0xAF05:"HÔ HÔ, ĐẨY ĐÓ",0xAF0F:"NÀY~ ĐẨY ĐÓ!",
0xAF19:"HÔ HÔ HÔ HÔ HÔ",0xAF25:"Ơ, DÁM À?",0xAF30:"NÀY~ CÁI GÌ!!",0xAF3C:"IM NGAY, NHÓC!",0xAF4D:"MỚI BẮT ĐẦU!",0xAF5B:"D-D-DÁM À~!!",
0xAF69:"LIÊN HOÀN NÈ!",0xAF77:"CÔ THẮNG RỒI!!",0xAF83:"ÁÁÁ… TH-THUA…",0xAF90:"TỚI ĐÂY, SHIN!",0xAF9E:"ĐƯỢC, ĐẨY ĐÂY!",0xAFAD:"ỪM, THUẬN LỢI!",
0xAFBB:"CỐ THÊM CHÚT!!",0xAFC9:"HỰ, GIỎI LẮM!",0xAFD1:"HỰ, KHÁ LẮM!",0xAFDF:"N-NGUY HIỂM!!",0xAFEC:"ACTION BEAM!!",0xAFF7:"TRỜI ĐẤT ƠI!",
0xB004:"LIÊN HOÀN ĐÂY!",0xB013:"HA HA HA HA!!",0xB01F:"ỪM… TA THUA.",0xB0E5:"DEMO ĐÓ NHA!",0xB0F3:"BẤM START ĐI?",
}
D1BIG = {
0xB02B:"TỚ CŨNG KHÁ ĐẤY CHỨ! TIẾP THEO CHƠI KHÓA THƯỜNG NÀO!!",0xB04E:"TRONG ĐÁM BẠN, TỚ LÀ SỐ MỘT! TIẾP THEO LÀ KHÓA GIỎI!!",
0xB076:"Ở NHÀ TRẺ TỚ VÔ ĐỊCH! TIẾP THEO THỬ THÁCH KHÓA THIÊN TÀI!!",0xB0A3:"Ồ! TỚ LÀ VUA GIẢI ĐỐ RỒI!! HA HA HA HA HA!!",
}
STAGES = [["CHƠI VỚI SHIRO","MẸ NENE HIỀN LẮM","GIÚP MẸ LÀM VIỆC"],["CHƠI VỚI MASAO","ĐỒ HÀNG VỚI NENE","ALBUM CỦA KAZAMA"],
          ["CÔ YOSHINAGA BẬN","CÔ MATSUZAKA ĐÂY","GIÚP ÔNG TRÙM"],["LÀM ACTION KAMEN"]]
